# Generated by Django 3.0.14 on 2022-06-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MPSHTraffic',
            fields=[
                ('hour', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NumberOfReadings',
            fields=[
                ('hour', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='USCTraffic',
            fields=[
                ('hour', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UTTraffic',
            fields=[
                ('hour', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WellnessTraffic',
            fields=[
                ('hour', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
